name: Bug Report
description: Report a bug
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: |
        1. Set environment...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        OS: 
        Docker version: 
        MCP client: Claude Code
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs (remove sensitive data)
      placeholder: Paste error messages here...