name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: textarea
    id: summary
    attributes:
      label: What feature do you want?
      placeholder: Brief description of the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why do you need this?
      placeholder: What problem would this solve?...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Trading Operations
        - Market Data
        - Configuration
        - Documentation
        - Other
    validations:
      required: true